### ISSUE TITLE
VerliHub 1.4.0.0 - problem with start under debian 10/11 (LXC env)

### ISSUE THREAD

**Issue by Aminuxer** [Verlihub/verlihub#201]
I try update 1.3.0.0 to 1.4.0.0 by make / make install and new version crashed.

!! At first, file /usr/local/share/verlihub/sql/default_pi_chatroom.sql  not created at install process;

I try create this file and even add query for add string to pi_chatroom table, but next error occured in strace:

$ export LD_LIBRARY_PATH=/usr/local/lib && strace /usr/local/bin/vh -r

write(2, "nMySQL::cQuery", 14nMySQL::cQuery)          = 14
write(2, " - ", 3 - )                      = 3
write(2, "Error in query ~", 16Error in query ~)        = 16
write(2, "select auto_cc, auto_class_max, "..., 88select auto_cc, auto_class_max, auto_class_min, min_class, topic, nick from pi_chatroom ) = 88
write(2, "~", 1~)                        = 1
write(2, "\n", 1
)                       = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by RoLex** [comment]
Chatroom plugin is deprecated, it has not been updated for years. Ledokol chatroom feature replaces the plugin completely.

Secondly, how do you update Verlihub and how do you load plugins? Please show me the exact steps from first to last step. There is a very common mistake people do when they update hub and load plugins - that is loading old version of compiled plugin, which will always crash. Hub core is 1.4.0.0 and plugin is 1.3.0.0.

Regards.

**Comment by Aminuxer** [comment]
I simply download archive with sources release and make classic actions with ./configure | make | make install

I remove simlinks to plugins from /etc/verlihub/plugins, and verlihub started correctly

Current versions of plugins:
root@DC-TEST:/usr/local/lib# ls -l 
total 6084
-rw-r--r-- 1 root staff  163936 Apr 29 23:51 libchatroom_pi.so
-rw-r--r-- 1 root staff   85744 Apr 29 23:52 libfloodprot_pi.so
-rw-r--r-- 1 root staff  165792 Apr 29 23:51 libforbid_pi.so
-rw-r--r-- 1 root staff   95976 Apr 29 23:52 libiplog_pi.so
-rw-r--r-- 1 root staff  194120 Apr 29 23:52 libisp_pi.so
-rw-r--r-- 1 root staff  291080 May 23 16:56 liblua_pi.so
-rw-r--r-- 1 root staff  115928 Apr 29 23:52 libmessenger_pi.so
-rw-r--r-- 1 root staff  179600 May 23 16:56 libplug_pi.so
-rw-r--r-- 1 root staff  213216 May 23 16:57 libpython_pi.so
-rw-r--r-- 1 root staff   98632 Apr 29 23:52 libreplacer_pi.so
-rw-r--r-- 1 root staff   79800 Apr 29 23:52 libstats_pi.so
-rw-r--r-- 1 root staff 2020256 May 23 16:56 libverlihub.so
lrwxrwxrwx 1 root staff      22 Aug  4  2016 libverlihub.so.1.0.0 -> libverlihub.so.1.0.0.0
-rw-r--r-- 1 root staff 2262304 Aug  4  2016 libverlihub.so.1.0.0.0
-rw-r--r-- 1 root staff   83256 May 23 16:56 libvh_python_wrapper.so
-rw-r--r-- 1 root staff   80472 May 23 16:56 libvhapi.so
lrwxrwxrwx 1 root staff      19 Aug  4  2016 libvhapi.so.1.0.0 -> libvhapi.so.1.0.0.0
-rw-r--r-- 1 root staff   66328 Aug  4  2016 libvhapi.so.1.0.0.0

But without plugins hub-menu and some features don't work. How to fix plugins problem ?

**Comment by RoLex** [comment]
Exactly, `./configure` is the old way of compiling, before CMake was added about 12 (?) years ago. If you read the manual ( https://github.com/verlihub/verlihub/wiki/installation#preparing-and-compiling-the-source ), you will see a list of `cmake .. && make && make install`. When executing `cmake ..` you are given the options to enable/disable required plugins. By default only Lua and Plugman plugins are compiled, the rest of them are deprecated and are not built by default, meaning that your `libchatroom_pi.so` is outdated - it's from previous version 1.3.0.0, which will cause a crash for sure.

`liblua_pi.so` symlink should not be placed into `/etc/verlihub/plugins`, the only autoloaded (by symlink) plugin should be Plugman. This is because Plugman itself is a plugin manager with a set of commands (`Plugins` section in `!help`). It is specially designed to manage plugins. As of Lua plugin autoload, there is a `-a` option for autoloading a plugin on startup, `!modplug lua -a 1`.

Lets say it like this when it comes to need or don't need one or other plugin.. All plugins except Plugman and Lua are deprecated, the code has not been touched for 10 years, they all will crash your hub in one or another way. This is because Ledokol Lua script ( https://ledo.feardc.net ) and Verlihub itself has completely replaced all the functionality in the old plugins.
